name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 1 * * 0'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  
      - 
        name: Download and Unzip Upstream Source Code
        id: download
        run: |
          VERSION=$(curl --silent "https://api.github.com/repos/lsky-org/lsky-pro/releases" | grep "tag_name" | head -n 1 | awk -F ":" '{print $2}' | sed 's/\"//g;s/,//g;s/ //g')
          URL_INFO=https://github.com/lsky-org/lsky-pro/archive/refs/tags/${VERSION}.zip
          curl -OL ${URL_INFO}
          unzip ${VERSION}.zip
          mv ./lsky-pro-${VERSION}/* ./
          mv ./lsky-pro-${VERSION}/.env.example ./
          rm -rf ${VERSION}.zip lsky-pro-${VERSION}
          run: echo ::set-output name=latest_tag::${VERSION}
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }} 
      -  
        name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/lsky-pro
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64, linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.download.outputs.latest_tag }}
          labels: ${{ steps.meta.outputs.labels }}
